<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $fillable = [
        'name', 'championship_id', 'user_id'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($team){
            $team->sheets()->delete();
            $team->statistic()->delete();
        });
    }

    public function getRouteKeyName()
    {
        return 'name';
    }

    public function championship()
    {
        return $this->belongsTo(Championship::class);
    }

    public function statistic()
    {
        return $this->hasMany(Statistic::class);
    }

    public function sheets(){
        return$this->hasMany(Sheet::class);
    }

}
